### ISSUE TITLE
Empty default in schema is parsed as null

### ISSUE THREAD

**Issue by jason-cohen** [swagger-api/swagger-parser#814] opened 2018-08-24 17:24 UTC
#### Parser version:
2.0.2
#### Description:
OAS 3 spec (partial): 
```yaml
components:
  parameters:
    example:
      name: example
      description: example
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
        default: ''
```

The parameter schema parser treats empty strings as null.

`schema.getDefault()` returns `null`.

The following results in a proper default value being set:
```yaml
components:
  parameters:
    example:
      name: example
      description: example
      in: query
      required: false
      schema:
        type: array
        items:
          type: string
        default: 'a,b,c'
```

`schema.getDefault()` returns `"a,b,c"`.

**Comment by webron** [comment] 2018-08-25 21:41
The first case is not really a valid definition. You're setting that the default value for the array is an empty string, but the spec requires the type of the `default` to correspond to the type it refers to.

The second case is actually also not really valid, because again it's a string and not an array, but we seem to parse it still so that's actually a bug.

**Comment by jason-cohen** [comment] 2018-08-26 12:14
@webron I see what you mean. In that case, I've got a follow question though. 

How would you go about specifying an empty list as a default? The lack of the default field in the spec would obviously signal the that field can't be parsed, but your suggesting that an empty string is am invalid entry. 

I'll adjust the PR #894 when I get more clarification on how to proceed.

**Comment by webron** [comment] 2018-08-26 15:03
That's where it gets complicated. Not sure there is a way to do it, as it's an edge case.

Theoretically, you could set the default value to `[]` which is indeed an empty JSON array. However, the value of the array in this case is not a JSON, especially with the defaults for query parameters having `style: form`, `explode: true` by default - suggesting there's no real way of representing that. I'd recommend filing a ticket on the spec asking that question. We may simply agree that a JSON array value would be representative of such values regardless of how those are being converted to the request.

That said, in your specific example, one might argue that there's no point providing a default value of an empty array as it most likely does not affect the documentation nor implementation.

**Comment by gracekarina** [comment] 2018-08-26 18:06
Hi I have created and issue, @jason-cohen if you can please provide an spec so we can work on it.

**Comment by jason-cohen** [comment] 2018-08-28 17:41
@webron Here's how we came about this issue.

In our API-first approach, after defining the spec, we use code generation for a spring-boot service stub (OpenApi-generator now, swagger-codegen before). When attempting to use optional list query parameters like in my original message above, we noticed a non-related bug with how defaults were being handled in the service-stub.

```@RequestParam(value="example", required=false, defaultValue="new ArrayList<>()")```

In digging a bit to resolve that issue, I noticed that when I used a default value of `a,b,c` in the spec, I received the proper format in my RequestParam annotation - by coincidence of doing `toString()`.

However when I left the default value empty in the spec - `defaultValue: ''` then the RequestParam didn't have the defaultValue set. This stemmed from the null field in the swagger-parser `Schema` object.

So my intent was to produce a non-null default value in the swagger-parser `Schema` if the field was present in the spec, in order to address the needs further downstream with the codegen.

As you've pointed out, I was misplaced in my presumption of default values in the OAS3 spec.

Even if arrays are an edge case, and lack clarification in the spec in how to address them, I still feel the bug is valid though. Just substitute the array type for a `string` schema, and an empty string default value should be considered valid. It may seem redundant or unnecessary to define an empty string/list as a default value in the spec, but the swagger-parser should simply take it as face value and - upon type validation, etc. - produce a code copy of what was defined in the spec.

@gracekarina I created this gist with a spec involving an assortment of potential default value scenarios:
https://gist.github.com/jason-cohen/3347305ab317970058f3a4571373357b#file-swagger-parse-814-yml

**Comment by webron** [comment] 2018-08-29 23:58
But how is the bug valid if it's not a bug? I mean, we can be less lenient and instead of setting it to a `null` value, just throw an exception and fail the entire parsing, but that seems like an even worse solution. What you're describing in the definition is simply not valid. And if it were a string type, with an empty string value, then it should work as you'd expect.

It sounds like you're trying to solve a bug in the codegen by creating a bug in the parser - and that's backwards.

**Comment by gracekarina** [comment] 2019-06-20 01:37
Hi, the scope of the issue changed, the validation of this new scope made in another PR. Thanks @jason-cohen for reporting this and sorry for the long reply. I will close this because is no longer an issue.

**Closed by gracekarina** 2019-06-20 01:37 UTC
