### ISSUE TITLE
HTTP 400 when following URLs with path parameters in swagger doc

### ISSUE THREAD

**Issue by ludyte** [swagger-api/swagger-parser#93] opened 2015-09-16 21:46 UTC
Using swagger-codegen to read a swagger spec that aggregates other specs with path parameters in the URL, an HTTP 400 is raised because the '{' '}' that delimit the path parameter are not properly encoded by io.swagger.parser.util.RemoteUrl.   

This occurs when the Swagger parser determines that the relative path to a resource is described by a string that looks like a URL and it tries to read the contents of the URL into the parser.

```
java.io.IOException: Server returned HTTP response code: 400 for URL: http://127.0.0.1:8075/api/api-docs/v1/service/{parameter}/otherapi
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1838)
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1439)
    at io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:100)
    at io.swagger.parser.SwaggerCompatConverter.readDeclaration(SwaggerCompatConverter.java:451)
    at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:133)
    at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:36)
    at io.swagger.codegen.Codegen.main(Codegen.java:85)
```

**Comment by webron** [comment] 2015-09-21 15:15
Are you referring to a 1.2 definition?

**Comment by ludyte** [comment] 2015-09-22 02:14
yes.   The stack trace shows the exception being raised from the compat parser.  I have a patch that's working for me, though its a bit of a hack.

**Comment by ludyte** [comment] 2015-09-22 02:43
Atleast it was until I rebased.   hack hack hack..

**Comment by webron** [comment] 2015-09-22 13:29
Yup, the problem is that it's not really a valid 1.2 definition. There's already a pending PR for a workaround, we'll see which one gets merged.

**Comment by ChrLipp** [comment] 2016-01-14 14:14
May I ask what's the state of this? I encounter the same error as ludyte and I am working currently with his PR code which works fine. I was surprised that parsing URLs with path parameters does not work with the generator.

**Comment by fehguy** [comment] 2016-01-14 19:18
I don't quite see why this is an issue.  As @webron said, it's not even a valid definition in the 1.2 specification.

Think of it like this.  In 1.2 (and prior), there was a Resource Listing, which held pointers to Api Declarations.  There is no reason why you would have a path parameter in the location of an api declaration, so there is no reason why the parser code would try to substitute a value for it.  What value would it even substitute with?

**Comment by ChrLipp** [comment] 2016-01-15 09:21
The parser doesn't have to substitute a value for the path parameter. For example the index spec contains a link with a path parameter like http://host/service/api/api-docs/v1/persons/{personId}/ and the parser uses this link 1:1 which leads to the http 400 error. When the PR is applied the parsers encodes the link and therefore is able to read the sub spec: http://host/service/api/api-docs/v1/persons/%7BpersonId%7D/

I don't understand what this has to do with the 1.2 spec, path params are used in almost every service and the code generator should be able to read the specifications.

**Comment by fehguy** [comment] 2016-01-15 14:40
OK it is fair that it escapes those characters.  But again, it is meaningless to have a path substitution when reading a spec.  This has nothing to do with calling a service, typically a service is called _after_ substituting a value for a path parameter.

But for what you raise, yes, we can update the code to encode `{|}`.

**Closed** 2016-12-27 07:01 UTC
