### ISSUE TITLE
Support *.yml files as yaml format

### ISSUE THREAD

**Issue by gustavorodrig** [swagger-api/swagger-parser#318] opened 2016-10-26 13:42 UTC
Swagger parser is only considering *.yaml files when parsing, for some reason many companies uses *.yml in their swagger projects..

I modified the code to consider *.yml as YAML format and I will do a pull request to project.

**Comment by fehguy** [comment] 2016-10-26 15:02
This is a duplicate of #317

**Closed by fehguy** 2016-10-26 15:02 UTC
