### ISSUE TITLE
Swagger-parser build failure issue: java.nio.file.InvalidPathException: Illegal char <:> at index 4: file://src/test /resources/uber.json

### ISSUE THREAD

**Issue by pavitrapapanna** [swagger-api/swagger-parser#142] opened 2015-11-25 08:32 UTC
Hi,
I was using swagger-parser 1.0.13 version ,but parameter "type" is not supporting for this. so downloaded latest 1.0.14 snaphot version.Build is not successful for this latest version.Build failure due to  test case failure.Stack trace given below while issuing mvn clean install is as fallows:

reading from uber.json
Configuring TestNG with: TestNG652Configurator
Tests run: 76, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 6.302 sec <<< F
AILURE! - in TestSuite
readUberApiFromFile(io.swagger.parser.SwaggerReaderTest)  Time elapsed: 0.01 sec
  <<< FAILURE!
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file://src/test
/resources/uber.json
        at java.nio.file.Paths.get(Paths.java:84)
        at io.swagger.parser.util.PathUtils.getParentDirectoryOfFile(PathUtils.j
ava:9)
        at io.swagger.parser.ResolverCache.<init>(ResolverCache.java:54)
        at io.swagger.parser.SwaggerResolver.<init>(SwaggerResolver.java:26)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:52)
        at io.swagger.parser.SwaggerReaderTest.readUberApiFromFile(SwaggerReader
Test.java:19)

Results :

Failed tests:
  SwaggerReaderTest.readUberApiFromFile:19 ╗ InvalidPath Illegal char <:> at ind
...

Tests run: 76, Failures: 1, Errors: 0, Skipped: 0

**Comment by wing328** [comment] 2015-11-25 15:25
I pull the latest master and `mvn clean install` works for me. Would that work for you?

**Comment by fehguy** [comment] 2015-11-28 02:48
I cannot reproduce this either.  Please reopen if you're still having trouble.

**Comment by ManojDhanorkar** [comment] 2015-12-24 13:41
Same issue faced by me ...


reading from src/test/resources/petstore.json
reading from src/test/resources/troublesome.yaml
reading from minimal_j
reading from minimal_y
reading from sampleWithMinimumValues.yaml
reading from sampleWithMinimumValues.yaml
reading from uber.json
reading from file://src/test/resources/uber.json
reading from issue_16.yaml
reading from issue_469.json
reading from uber.json
Configuring TestNG with: TestNG652Configurator
Tests run: 79, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 19.389 sec <<< FAILURE! - in TestSuite
testIssue75(io.swagger.parser.SwaggerParserTest)  Time elapsed: 0.03 sec  <<< FAILURE!
java.lang.AssertionError: expected [true] but found [false]
        at io.swagger.parser.SwaggerParserTest.testIssue75(SwaggerParserTest.java:67)

readUberApiFromFile(io.swagger.parser.SwaggerReaderTest)  Time elapsed: 0.04 sec  <<< FAILURE!
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file://src/test/resources/uber.json
        at java.nio.file.Paths.get(Paths.java:84)
        at io.swagger.parser.util.PathUtils.getParentDirectoryOfFile(PathUtils.java:9)
        at io.swagger.parser.ResolverCache.<init>(ResolverCache.java:54)
        at io.swagger.parser.SwaggerResolver.<init>(SwaggerResolver.java:26)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:52)
        at io.swagger.parser.SwaggerReaderTest.readUberApiFromFile(SwaggerReaderTest.java:19)


Results :

Failed tests:
  SwaggerParserTest.testIssue75:67 expected [true] but found [false]
  SwaggerReaderTest.readUberApiFromFile:19 » InvalidPath Illegal char <:> at ind...

Tests run: 79, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] swagger-parser-project ............................. SUCCESS [01:02 min]
[INFO] swagger-parser ..................................... FAILURE [01:10 min]
[INFO] swagger-compat-spec-parser ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:13 min
[INFO] Finished at: 2015-12-24T19:09:04+05:30
[INFO] Final Memory: 34M/355M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.18.1:test (test-testng) on project swagger-parser: There are test failures.
[ERROR]
[ERROR] Please refer to D:\LBS\MWM 2.3\SwaggerPars\swagger-parser-master\swagger-parser-master\modules\swagger-parser\target\surefire-reports for the individual test resul
ts.

**Comment by fehguy** [comment] 2015-12-27 14:14
Looks like a windows-specific issue.

**Comment by fehguy** [comment] 2016-10-27 19:22
This should be fixed now.

**Closed by fehguy** 2016-10-27 19:22 UTC

**Comment by josebarroszeiss** [comment] 2024-02-15 12:26
Not fixed it still happens.
