### ISSUE TITLE
Open API parser is not validating the invalid references

### ISSUE THREAD

**Issue by saileshsingh** [swagger-api/swagger-parser#934] opened 2018-11-15 12:48 UTC
Hi,

First of all, thanks a lot for the excellent product.

PFB,
responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"

As mentioned above, If my Open API file doesn't have any schema with name ApiResponse under components/schemas then Open API parser should report the missing references and this case is applicable for all other component types as well.

Regards,
Sailesh V

**Comment by pureJEagles** [comment] 2018-11-29 14:35
Actually, it might be a duplicate of #684 but the fix doesn't seem to be on master or in the 3.3.3 release.

**Comment by gracekarina** [comment] 2019-01-27 23:14
Closed by #935

**Closed by gracekarina** 2019-01-27 23:14 UTC
