### ISSUE TITLE
Swagger JSON incorrectly read using system default encoding instead of UTF-8

### ISSUE THREAD

**Issue by benken-parasoft** [swagger-api/swagger-parser#21] opened 2015-03-05 18:39 UTC
If a Swagger document has non-ascii characters then those characters are not read correctly by the parser.  A Swagger document should probably be encoded UTF-8 because this is the default for JSON.  From https://tools.ietf.org/html/rfc7159#section-8.1:
"JSON text SHALL be encoded in UTF-8, UTF-16, or UTF-32.  The default encoding is UTF-8"

The problem is in io.swagger.parser.util.RemoteUrl.  It calls the InputStreamReader constructor that uses the default system charset.  This will not necessarily be UTF-8, especially on Windows OS.  It should use the InputStreamReader constructor where you can specify both an InputStream and a charsetName.

**Comment by webron** [comment] 2015-03-05 18:56
Fair point. Can you submit a PR to fix it?

**Comment by benken-parasoft** [comment] 2015-03-05 19:35
Forgive my ignorance but I thought this is the place to file issues.  I could not find a jira or bugzilla for this swagger project if there is a different place to submit issues.  As mentioned, the issue is in the RemoteUrl class which is part of this project.

**Comment by webron** [comment] 2015-03-05 20:06
No worries. A PR in github is short for 'Pull Request' - it's basically an actual code change to fix the problem. Since it looks like you investigated exactly where the problem occurs and how it should be fixed, you can probably easy share a code change with us so we can merge. The PRs really help us move forward as we are limited on manpower and it helps pushing things forward. If you can't make a PR, that's absolutely fine as well. Opening the issue is a huge help as well.

**Comment by benken-parasoft** [comment] 2015-03-05 20:13
Thanks.  I am confusing "pull request" vs "problem report".

**Comment by webron** [comment] 2015-03-05 20:19
It's just common github lingo. Do you think you could provide a PR? If so, make sure it's against the `develop` branch.

**Comment by benken-parasoft** [comment] 2015-03-05 22:51
I wish I had the time.  :)  I am working around the issue right now.  One possible workaround is to pass -Dfile.encoding=UTF-8 when starting java.  However, this is not very convenient and not something I want to do.

I am working around the issue in a more complex way.  I have my own custom subclasses of SwaggerCompatConverter and Swagger20Parser, overriding the methods that use RemoteUrl so I can make them use my own custom version of RemoteUrl that is using "UTF-8" when constructing the InputStreamReader.  In general, I have taken this approach of creating my own subclasses to work around issues like this one.  I look forward to using the parser classes as-is when the outstanding issues are fixed.

**Comment by webron** [comment] 2015-03-05 22:53
Sounds like it would have taken less time to modify the current code and submit a PR ;) Just kidding. We'll try to get around to it soon.

**Closed** 2015-03-19 00:23 UTC
Labels: P2
