### ISSUE TITLE
Relative references from a URL to a file in the parent folder throw error (OAS2)

### ISSUE THREAD

**Issue by ymohdriz** [swagger-api/swagger-parser#713] opened 2018-05-17 05:48 UTC
Hi team,

I have a file hosted in server say http://mcmriz01:5555/WmAPIGateway/validpath/service/serviceA.yaml in which refA.yaml (http://mcmriz01:5555/WmAPIGateway/validpath/refA.yaml) is referred 
paths:
  /test:
    get:
      responses:
        '200':
          schema:
            $ref: '../refA.yaml'

Error: Unable to load RELATIVE ref: ../refA.yaml
Note: This is not working when the input is url, works fine for a input file

Thanks,
Mohammed

**Comment by gracekarina** [comment] 2018-05-23 16:04
Hi, @ymohdriz which version of parser are you using?

**Comment by gracekarina** [comment] 2018-08-03 02:48
Hi @ymohdriz can you please try one of these branches to test your issue?
version 2.0 = `fix-relative-resolving` (depends on core's `ref-refactor` branch)
version 3.0 = OAS3-relative-resolving

**Comment by cvgaviao** [comment] 2020-08-21 01:30
@gracekarina, I was bitten by this error right now. 
```
[ERROR] unable to read
java.io.FileNotFoundException: https://gitlab.com/api/v4/projects/20509299/repository/files/oas3%2Fc8tech.mmarket.oas3.admin.internal.yaml/c8tech.mmarket.oas3.common.internal.yaml
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1964)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1963)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1531)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at io.swagger.v3.parser.util.RemoteUrl.urlToString(RemoteUrl.java:152)
	at io.swagger.v3.parser.util.RefUtils.readExternalRef(RefUtils.java:204)
	at io.swagger.v3.parser.util.RefUtils.readExternalUrlRef(RefUtils.java:112)
	at io.swagger.v3.parser.ResolverCache.loadRef(ResolverCache.java:122)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalResponse(ExternalRefProcessor.java:344)
	at io.swagger.v3.parser.processors.ResponseProcessor.processReferenceResponse(ResponseProcessor.java:84)
	at io.swagger.v3.parser.processors.ResponseProcessor.processResponse(ResponseProcessor.java:41)
	at io.swagger.v3.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:56)
	at io.swagger.v3.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:84)
	at io.swagger.v3.parser.OpenAPIResolver.resolve(OpenAPIResolver.java:49)
	at io.swagger.v3.parser.OpenAPIV3Parser.readLocation(OpenAPIV3Parser.java:67)
	at io.swagger.parser.OpenAPIParser.readLocation(OpenAPIParser.java:16)
	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:510)

```

**Comment by cvgaviao** [comment] 2020-08-26 16:02
> Hi @cvgaviao, please send a spec or a sample where we can reproduce and test the issue. Thanks!

@gracekarina, I've found that the issue I'm facing is not spec dependent. 

It is caused by the way we mount a URL to access a spec hosted in a Gitlab's private repository. see a better description [here](https://stackoverflow.com/questions/63524424/how-to-resolve-a-relative-path-in-gitlab-raw-accessed-file)

**Comment by webron** [comment] 2021-01-22 02:30
Closing the ticket due to lack of activity. If anyone experiences a similar issue, please file a new ticket providing the relevant details.

**Closed by webron** 2021-01-22 02:30 UTC
