### ISSUE TITLE
Duplicated schemas in parsed result

### ISSUE THREAD

**Issue by ackintosh** [swagger-api/swagger-parser#1081] opened 2019-04-20 09:32 UTC
Related issue: https://github.com/OpenAPITools/openapi-generator/issues/2701

---

### Specs that reproduces the issue

- openapi.yaml

```yaml
openapi: 3.0.0
info:
  title: Common Data Types
  version: "1.0"
paths:
  /subscriptions:
    get:
      summary: read all of the active subscriptions for the app.
      operationId: getSubscriptionsById
      parameters:
        - name: appId
          in: path
          description: App ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK (Successful)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
        '500':
          $ref: './common.yaml#/components/responses/E500'  
components:
  schemas:
      ProblemDetails:
        type: object
        properties:
          title:
            type: string
            description: A short, human-readable summary of the problem
          status:
            type: integer
            description: The HTTP status code for this occurrence of the problem.
      Subscription:
        type: string
```

- common.yaml

```yaml
openapi: 3.0.0
info:
  title: Common Data Types
  version: "1.0"
paths: {}
components:
  responses:
    E500:
      description: Server Error
      content:
        application/json:
          schema:
            $ref: './openapi.yaml#/components/schemas/ProblemDetails'
```

### Test codes which shows the issue

- OpenAPIV3ParserTest.java

```java
    @Test
    public void fooBar() {
        String location = "src/test/resources/xxx/openapi.yaml";
        OpenAPIV3Parser parser = new OpenAPIV3Parser();

        OpenAPI result = parser.read(location);
    }
```

The `result` has a duplicated schema `ProblemDetails_2`.

![image](https://user-images.githubusercontent.com/1885716/56455426-1b428080-6399-11e9-9e48-b35832efdf89.png)

**Comment by r-sreesaran** [comment] 2019-05-16 09:21
@ackintosh  can you add a failing test case.

**Comment by ackintosh** [comment] 2019-05-18 07:15
@r-sreesaran Thanks for your reply. I've filed the PR to add a failing test case.
https://github.com/swagger-api/swagger-parser/pull/1102

**Comment by r-sreesaran** [comment] 2019-06-06 09:41
@ackintosh  This may be valid as "Problem Details" is referenced from external open api document. It needs to be duplicated and added in the object. 

Consider a case where there are two schema having same name but of different type. Then in that case if we remove duplicate, then one schema will be lost.  

Here the Problems Details are present in both documents and have different definitions.
If we remove the duplicate entries then only one schema will be present. But we need both. 
 
```openapi: 3.0.0
info:
  title: Common Data Types
  version: "1.0"
paths:
  /subscriptions:
    get:
      summary: read all of the active subscriptions for the app.
      operationId: getSubscriptionsById
      parameters:
        - name: appId
          in: path
          description: App ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK (Successful)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
        '500':
          $ref: './issue-1108-1.yaml#/components/responses/E500'
        '501':
          $ref: '#/components/schemas/ProblemDetails' 
components:
  schemas:
    ProblemDetails:
      type: object
      properties:
        title:
          type: string
          description: A short, human-readable summary of the problem
        status:
          type: integer
          description: The HTTP status code for this occurrence of the problem.
    Subscription:
      type: string
```

issue-1108-.yaml
```
openapi: 3.0.0
info:
  title: Common Data Types
  version: "1.0"
paths: {}
components:
  responses:
    E500:
      description: Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
  schemas:
   ProblemDetails:
      type: object         
```

@gracekarina  @ymohdriz  please do share your comments on this issue.

**Comment by gracekarina** [comment] 2019-06-06 12:34
Hi @r-sreesaran thanks for the reply, the case @r-sreesaran presents it's the same schema, so it should not be duplicating it. The case you present above it's ok for "duplicating" because there are different schemas. Sorry it's taking long for me to check this, I hope to have a fix for this week.

**Comment by ymohdriz** [comment] 2019-06-07 09:39
@r-sreesaran Issue here is a new schema (ProblemDetails_2) is introduced in the components which is incorrect. We need to fix it

**Comment by r-sreesaran** [comment] 2019-06-12 07:06
@gracekarina  Few clarifications about the  duplication part from the example i have mentioned. As per Open API specification no two schema definitions can have the same name. Since these references are added from the same file this does qualify them to be treated as schemas from same document and in such case the open api document becomes invalid as there two schemas with name name. 

As of now we are not handling the references like wise. 
Should this be done this way or in existing way where a different name is created and then the schema is added using the created name.

**Comment by r-sreesaran** [comment] 2019-06-13 08:00
After reading through some resources, I was able to find out according to RFC7159. We cannot have duplicate keys present.  https://tools.ietf.org/html/rfc7159#section-4. 
I will raise a PR like wise.

**Comment by jphorx** [comment] 2019-06-25 18:25
We've seen this issue as well using version 2.0.12.  These two swagger files can be used to reproduce it if needed and will produce two models for flowDirection.

**spec1.yaml**
```
openapi: "3.0.0"
info:
  version: 1.0.0
  title: spec1
paths:
  /flow:
    get:
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlowInformation'
components:            
  schemas:
    FlowDirection:
      enum:
        - DOWNLINK
        - UPLINK
        - BIDIRECTIONAL
        - UNSPECIFIED
    FlowInformation:
      type: object
      properties:
        flowDescription:
          $ref: 'spec2.yaml#/components/schemas/FlowDescription'
        ethFlowDescription:
          $ref: 'spec2.yaml#/components/schemas/EthFlowDescription'
        flowDirection:
          $ref: '#/components/schemas/FlowDirection'
```

**spec2.yaml**
```
openapi: "3.0.0"
info:
  version: 1.0.0
  title: spec2
components:            
  schemas:
    FlowDescription:
      type: string
    EthFlowDescription:
      type: object
      properties:
        fDesc:
          $ref: '#/components/schemas/FlowDescription'
        fDir:
          $ref: 'spec1.yaml#/components/schemas/FlowDirection'
```

**Comment by binaryunary** [comment] 2020-02-05 09:41
I'm cross-posting my comment from an issue in openapi-generator as the issue is related to swagger-parser. Original link: https://github.com/OpenAPITools/openapi-generator/issues/2701#issuecomment-582320928.

> After playing around with external refs for a bit I discovered that swagger-parser will do some normalization on them, but it seems to happen lazily.
> 
> If you have a ref like 
> 
> ```
> somefile.yml#/components/schemas/SomeSchema
> ```
> 
> then it will become
> 
> ```
> ./somefile.yml#/components/schemas/SomeSchema
> ```
> 
> inside the parser _after_ the first time this ref is resolved.
> Internally `SomeSchema` is cached when it is first read, when accessed the second time its source is different (`somefile.yml != ./somefile.yml`) so a number is appended to its name to avoid conflicts.
> 
> Prefixing relative paths with `./` solves this problem, but it seems the parser still has problems normalizing the paths relative to the root spec file as having complex relative references (e.g. different levels, from different subdirectories) still break the parser.

**Comment by schlagi123** [comment] 2020-04-01 10:31
The Issue #1292 resolves this issue. The current master branch works.

**Comment by gracekarina** [comment] 2020-04-01 14:47
yes that is true!, we solve the duplication issue, thanks for pointing this here! 
@ackintosh  please test and in case the issue is no longer happening please close.

**Comment by schlagi123** [comment] 2020-04-01 15:47
I tested the two examples from @ackintosh and @jphorx and they work. Please close the issue.

**Closed** 2020-04-01 16:43 UTC

**Comment by jimshowalter** [comment] 2020-12-07 19:26
We're using the latest versions of swagger-core, swagger-parser, and swagger-codegen:

io.swagger.codegen.v3:swagger-codegen-cli:3.0.23
io.swagger.codegen.v3:swagger-codegen:3.0.23
io.swagger.core.v3:swagger-annotations:2.1.5
io.swagger.core.v3:swagger-core:2.1.5
io.swagger.core.v3:swagger-models:2.1.5
io.swagger.parser.v3:swagger-parser-core:2.0.24
io.swagger.parser.v3:swagger-parser-v3:2.0.24
io.swagger.parser.v3:swagger-parser:2.0.24

But we still have this problem.

I'd happily preprocess our schema files if there's some way to munge them into a format that won't cause this.

What would the munged format need to look like?
