### ISSUE TITLE
Path Item Object $ref does not work as specified

### ISSUE THREAD

**Issue by mmannerm** [swagger-api/swagger-parser#149] opened 2015-12-15 01:15 UTC
Currently the $ref in Path Item Object does not work as specified. The $ref actually works under Operation Object (the spec does not allow it there), but not in the Path Item Object (where the spec says it should be allowed).

swagger.yml:

``` yml
swagger: '2.0'
info:
  version: 1.0.0
  title: 'Test REST API'
paths:
  "/test":
    $ref: './test.yml'
```

test.yml:

``` yml
get:
  description: Test request
  responses:
    '200':
      description: Successful response
```

Will result into:

```
[ERROR] Failed to execute goal io.swagger:swagger-codegen-maven-plugin:2.1.4:generate (default) on project swagtest: Execution default of goal io.swagger:swagger-codegen-maven-plugin:2.1.4:generate failed: An exception was thrown while trying to deserialize the contents of ./test.yml into type class io.swagger.models.Path: Unrecognized token 'get': was expecting ('true', 'false' or 'null')
[ERROR] at [Source: get:
[ERROR] description: Test request
[ERROR] responses:
[ERROR] '200':
[ERROR] description: Successful response
[ERROR] ; line: 1, column: 4]
[ERROR] -> [Help 1]
[ERROR] 
```

But, when you modify the swagger.yml to:

``` yml
swagger: '2.0'
info:
  version: 1.0.0
  title: 'Test REST API'
paths:
  "/test":
    get:
      $ref: './test2.yml'
```

and have test2.yml as:

``` yml
description: Test request
responses:
  '200':
    description: Successful response
```

It works. Unfortunately this makes it impossible to split swagger file into resource-specific files.

**Comment by Kabhal** [comment] 2016-01-20 10:42
Hello,

In my case, none of these solutions work :
- first solution : path totally ignored
- second solution : path used but path content is empty (no description, summary, etc...)

(I use https://github.com/Swagger2Markup/swagger2markup which internally use swagger-parser)

Any workaround/news for these $ref problems ?

**Comment by frantuma** [comment] 2016-02-01 10:56
@mmannerm I cannot reproduce with versions 2.1.5+, can you try using latest version?

**Comment by fehguy** [comment] 2016-12-27 07:02
This should be fixed

**Closed by fehguy** 2016-12-27 07:02 UTC
