### ISSUE TITLE
Unable to load RELATIVE ref: ./parameters.yaml

### ISSUE THREAD

**Issue by neuneuraxis** [swagger-api/swagger-parser#505] opened 2017-08-25 08:12 UTC
I'm starting with gradle plugin swagger2markup version 13.1.

I have this directory structure: 
```
- models
      |_ main.yaml
      |_ components
            |_ parameters.yaml
            |_ paths.yaml
- build.gradle 
```
The _main.yml_ references _paths.yaml_ and _paths.yaml_ references _parameters.yaml_.
When I launch the task `convertSwagger2markup --stacktrace`, I have this error:
```
Caused by: java.lang.RuntimeException: Unable to load RELATIVE ref: ./parameters.yaml
        at io.swagger.parser.util.RefUtils.readExternalRef(RefUtils.java:140)
        at io.swagger.parser.ResolverCache.loadRef(ResolverCache.java:94)
        at io.swagger.parser.processors.ParameterProcessor.processParameters(ParameterProcessor.java:37)
        at io.swagger.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:26)
        at io.swagger.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:93)
        at io.swagger.parser.SwaggerResolver.resolve(SwaggerResolver.java:40)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:66)
        at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:52)
        at io.github.swagger2markup.Swagger2MarkupConverter$Builder.readSwagger(Swagger2MarkupConverter.java:321)
        at io.github.swagger2markup.Swagger2MarkupConverter$Builder.<init>(Swagger2MarkupConverter.java:301)
        at io.github.swagger2markup.Swagger2MarkupConverter.from(Swagger2MarkupConverter.java:116)
        at io.github.swagger2markup.Swagger2MarkupConverter.from(Swagger2MarkupConverter.java:81)
        at io.github.swagger2markup.Swagger2MarkupConverter$from.call(Unknown Source)
        at io.github.swagger2markup.tasks.Swagger2MarkupTask.convertSwagger2markup(Swagger2MarkupTask.groovy:62)
        ... 114 more
Caused by: java.lang.RuntimeException: Could not find ./parameters.yaml on the classpath
        at io.swagger.parser.util.ClasspathHelper.loadFileFromClasspath(ClasspathHelper.java:31)
        at io.swagger.parser.util.RefUtils.readExternalRef(RefUtils.java:135)
        ... 127 more
```
I originally post a issue on Swagger2Markup/swagger2markup [(256),](https://github.com/Swagger2Markup/swagger2markup/issues/276) they said me to post a issue here.

**Comment by crankydillo** [comment] 2017-10-06 15:58
I am having a similar problem.  I'm pretty sure mine would be fixed if `pathToUse` or something like it was passed to `ClasspathHelper#loadFileFromClasspath`.  As [it's coded](https://github.com/swagger-api/swagger-parser/blob/develop/modules/swagger-parser/src/main/java/io/swagger/parser/util/RefUtils.java#L150), it's not using the parent directory to navigate into the classpath..

**Comment by saguinav** [comment] 2017-10-13 19:29
Same issue for me. Swagger-Parser doesn't manage folders and references well. As @crankydillo mentions the current implementation bases all references at the root swagger file level (in your case where your `main.yaml` is). So @neuneuraxis if you want to reference something from `parameters.yaml` in `paths.yaml` it has to be like `"$ref" : "./components/parameters.yaml"`. 

This bug has been around for a while, see #213 for instance. In fact, @crankydillo points [here](https://github.com/swagger-api/swagger-parser/issues/213#issuecomment-207400944) to some test files that IMO should fail, because they are referencing files that are not in the same directoy using `./`

**Comment by cabralje** [comment] 2017-11-06 21:26
Same issue.  As a work around, I'm consolidating all referenced files to a single directory.

**Comment by jorgerod** [comment] 2020-04-15 11:21
Any news?

**Comment by gracekarina** [comment] 2020-04-15 13:52
Please send spec sample to test. thanks

**Comment by jorgerod** [comment] 2020-04-16 11:10
Hi @gracekarina 

I use openapi-generator:4.3.0 maven plugin and forced swagger-parser:2.0.19.

I have checked that the relative paths in responses and responseBody work correctly #1343

Relative paths in parameters are not working (I don't check if relative paths in examples, links or headers are working)

**spec**

I have this directory structure:
```
project
    |-- openapi-rest.yml
    |-- components
        |-- paths.yml
        |-- parameters.yml
```


.openapi-rest.yml
```yaml
openapi: 3.0.0
info:
  version: 1.0.0
  title: Pruebas openAPI
  description: Pruebas openapi con referencias
servers:
  - url: http://localhost:8080
    description: Localhost
paths:
  /dummy-resource:
    $ref: 'components/paths.yml'
```

.paths.yml
```yml
get:
  operationId: get
  parameters:
    - name: myParam
      in: query
      description: Param
      required: true
      schema:
        $ref: 'parameters.yml#/components/schemas/DummyParam'
  responses:
    '200':
      description: My OK Response
```

.parameters.yml
```yaml
components:
  schemas:
    DummyParam:
      type: integer
      format: int32
      minimum: 0
      maximum: 100
```
Openapi-generator fails to generate and output the following.

```
[INFO] --- openapi-generator-maven-plugin:4.3.0:generate (generate-rest-api) @ rest-api-first-ws-api ---
[WARNING] Exception while reading:
java.lang.RuntimeException: Unable to load RELATIVE ref: parameters.yml path: C:\inditex\dev_openfwt_3x\rest-api-first\rest-api-first-ws-api\target\tmp\openapi\rest
    at io.swagger.v3.parser.util.RefUtils.readExternalRef (RefUtils.java:239)
    at io.swagger.v3.parser.ResolverCache.loadRef (ResolverCache.java:119)
    at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalSchema (ExternalRefProcessor.java:60)
    at io.swagger.v3.parser.processors.SchemaProcessor.processReferenceSchema (SchemaProcessor.java:214)
    at io.swagger.v3.parser.processors.SchemaProcessor.processSchema (SchemaProcessor.java:37)
    at io.swagger.v3.parser.processors.ParameterProcessor.processParameters (ParameterProcessor.java:145)
    at io.swagger.v3.parser.processors.OperationProcessor.processOperation (OperationProcessor.java:39)
    at io.swagger.v3.parser.processors.PathsProcessor.processPaths (PathsProcessor.java:84)
    at io.swagger.v3.parser.OpenAPIResolver.resolve (OpenAPIResolver.java:49)
    at io.swagger.v3.parser.OpenAPIV3Parser.readLocation (OpenAPIV3Parser.java:67)
    at io.swagger.parser.OpenAPIParser.readLocation (OpenAPIParser.java:16)
    at org.openapitools.codegen.config.CodegenConfigurator.toContext (CodegenConfigurator.java:455)
    at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput (CodegenConfigurator.java:501)
    at org.openapitools.codegen.plugin.CodeGenMojo.execute (CodeGenMojo.java:723)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: java.lang.RuntimeException: Could not find parameters.yml on the classpath
    at io.swagger.v3.parser.util.ClasspathHelper.loadFileFromClasspath (ClasspathHelper.java:31)
    at io.swagger.v3.parser.util.RefUtils.readExternalRef (RefUtils.java:233)
    at io.swagger.v3.parser.ResolverCache.loadRef (ResolverCache.java:119)
    at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalSchema (ExternalRefProcessor.java:60)
    at io.swagger.v3.parser.processors.SchemaProcessor.processReferenceSchema (SchemaProcessor.java:214)
    at io.swagger.v3.parser.processors.SchemaProcessor.processSchema (SchemaProcessor.java:37)

```

**Expected output:**
```java
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.inditex.demo.service;

import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "com.inditex.aqsw.framework.common.rest.server.codegen.AmigaSpringCodegen", date = "2020-04-16T11:27:26.907918500+02:00[Europe/Paris]")

@Validated
@Api(value = "Default", description = "the Default API")
public interface DefaultApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /dummy-resource
     *
     * @param myParam Param (required)
     * @return My OK Response (status code 200)
     */
    @ApiOperation(value = "", nickname = "get", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "My OK Response") })
    @RequestMapping(value = "/dummy-resource",
        method = RequestMethod.GET)
    default ResponseEntity<Void> get(@NotNull @Min(0) @Max(100) @ApiParam(value = "Param", required = true) @Valid @RequestParam(value = "myParam", required = true) Integer myParam) throws Exception {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}

```

**Related issues/PRs**
#1292 
#1343

**Comment by jorgerod** [comment] 2020-04-22 11:10
@gracekarina I can work on fix this issue .

**Comment by gracekarina** [comment] 2020-04-22 15:25
amazing! thanks! much appreciated.

**Comment by gracekarina** [comment] 2020-04-27 16:25
Fixed by #1358 
thanks @jorgerod.

**Closed by gracekarina** 2020-04-27 16:25 UTC

**Comment by CarstenLeue** [comment] 2020-05-26 08:06
@gracekarina could you please have a quick look at https://github.com/OpenAPITools/openapi-generator/issues/6320 and see if it might have been caused by this change? 

I would in particular be interested in your view on https://github.com/OpenAPITools/openapi-generator/issues/6320#issuecomment-629856539 since the use of relative references look inconsistent to me depending on whether a reference is used in a path reference or a schema reference. Shouldn't references be resolved consistently in all cases?

**Comment by PClegg-Software-Engineer** [comment] 2021-04-28 01:39
I didn't see it mentioned here so thought I'd add what solved this for me. I had the files referenced correctly but the case was off. Check your cases if all looks good.
